name: vdom
version: 0.4.0
author: Boris Kaul <localvoid@gmail.com>
description: Virtual DOM diff/patch.
homepage: https://github.com/localvoid/vdom
environment:
  sdk: '>=1.6.0'
dev_dependencies:
  browser: any
  unittest: any
