name: vdom
version: 0.1.0
author: Boris Kaul <localvoid@gmail.com>
description: Virtual DOM diff/patch.
homepage: https://github.com/localvoid/vdom
environment:
  sdk: '>=1.6.0'
dependencies:
  browser: any
  collection: any
dev_dependencies:
  unittest: any
