name: vdom
version: 0.3.0
author: Boris Kaul <localvoid@gmail.com>
description: Virtual DOM diff/patch.
homepage: https://github.com/localvoid/vdom
environment:
  sdk: '>=1.6.0'
dependencies:
  collection: '>=1.0.0 <2.0.0'
dev_dependencies:
  browser: any
  unittest: any
