name: vdom
version: 0.1.0
author: Boris Kaul <localvoid@gmail.com>
description: Virtual DOM diff/patch.
homepage: https://github.com/localvoid/vdom
environment:
  sdk: '>=1.6.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  collection: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: any
